# -*- coding: utf-8 -*-
import io, sys, os

p = os.environ.get("TARGET", "/srv/1111bot/run_bot.py")
s = io.open(p, encoding="utf-8").read()
fails = []

def rep(old, new, label):
    global s
    n = s.count(old)
    if n != 1:
        fails.append("FAIL: %s (found %d)" % (label, n))
        return
    s = s.replace(old, new)
    print("OK: " + label)

OLDREC = '        for rec in arr:\n            if rec.get("src") != "PENDING":\n                continue\n            iid = rec.get("iid"); pos = rec.get("pos")\n            if not iid or not pos:\n                continue\n            fpx = Decimal(rec.get("in_px") or "0")\n            size = Decimal("0")\n            g = fee = net = nv = xpx = None; src = None\n            ph = await close_record(iid, pos, int(rec.get("t0") or 0), tries=1)\n            if ph:\n                g, fee, net, nv, xpx = _from_ph(ph, size, Decimal("1"), fpx)\n                src = "OKX"\n            else:\n                od_out = await order_detail(iid, rec.get("xoid"), tries=1)\n                od_in = await order_detail(iid, rec.get("eoid"), tries=1)\n                if od_out and od_in:\n                    sz = od_out.get("sz") or Decimal("0")\n                    try:\n                        sp = await get_spec(rec["sym"])\n                        ctv = sp["ctval"]\n                    except Exception:\n                        ctv = Decimal("1")\n                    g, fee, net, nv, xpx = _from_orders(od_in, od_out, rec["dir"], sz, ctv)\n                    src = "訂單"\n            if src:\n                rec["gross"] = str(g); rec["fee"] = str(fee)\n                rec["net"] = str(net); rec["nv"] = str(nv)\n                rec["out_px"] = str(xpx); rec["src"] = src\n                rec["filled_at"] = hhmmss()\n                changed = True; filled += 1\n            await asyncio.sleep(0.2)\n'
NEWREC = '        for rec in arr:\n            if rec.get("src") != "PENDING":\n                continue\n            # 查詢鍵可能缺（舊紀錄），一律從 sym/dir/date/ts 推導，確保都能補\n            iid = rec.get("iid") or inst_id(rec.get("sym", ""))\n            pos = rec.get("pos") or ("long" if rec.get("dir") == "L" else "short")\n            t_ms = int(rec.get("t0") or 0) or _rec_epoch_ms(rec)\n            if not iid or not pos or not t_ms:\n                continue\n            try:\n                ctv = (await get_spec(rec["sym"]))["ctval"]\n            except Exception:\n                ctv = Decimal("1")\n            fpx = Decimal(rec.get("in_px") or "0")\n            g = fee = net = nv = xpx = None; src = None\n            ph = await _find_ph(iid, pos, t_ms)\n            if ph:\n                g, fee, net, nv, xpx = _from_ph(ph, Decimal("0"), ctv, fpx)\n                src = "OKX"\n            elif rec.get("xoid") and rec.get("eoid"):\n                od_out = await order_detail(iid, rec.get("xoid"), tries=1)\n                od_in = await order_detail(iid, rec.get("eoid"), tries=1)\n                if od_out and od_in:\n                    sz = od_out.get("sz") or Decimal("0")\n                    g, fee, net, nv, xpx = _from_orders(od_in, od_out, rec["dir"], sz, ctv)\n                    src = "訂單"\n            if src:\n                rec["gross"] = str(g); rec["fee"] = str(fee)\n                rec["net"] = str(net); rec["nv"] = str(nv)\n                rec["out_px"] = str(xpx); rec["src"] = src\n                rec["filled_at"] = hhmmss()\n                changed = True; filled += 1\n            await asyncio.sleep(0.2)\n'
FIND = 'def _rec_epoch_ms(rec):\n    """由紀錄的 date + ts 還原出場時刻（毫秒）。"""\n    try:\n        s = str(rec.get("date")) + " " + str(rec.get("ts"))\n        return int(datetime.strptime(s, "%Y-%m-%d %H:%M:%S").replace(tzinfo=TZ8).timestamp() * 1000)\n    except Exception:\n        return 0\n\nasync def _find_ph(iid, ps, t_ms, before=180000, after=1800000):\n    """在 positions-history 找出時間最接近 t_ms 的那筆平倉紀錄。"""\n    if not t_ms:\n        return None\n    r = await api("GET", f"/api/v5/account/positions-history?instType=SWAP&instId={iid}&limit=100")\n    if r.get("code") != "0":\n        return None\n    best = None; bd = None\n    for p in (r.get("data") or []):\n        if p.get("posSide") != ps:\n            continue\n        ut = int(p.get("uTime") or 0)\n        if ut < t_ms - before or ut > t_ms + after:\n            continue\n        dd = abs(ut - t_ms)\n        if bd is None or dd < bd:\n            best = p; bd = dd\n    return best\n\n'
OLDMAN = '            if not p_chk:\n                await notify(app, S["chat"], f"{E.BOT} {S[\'sym\']} {E.dir_word(d)} OKX 已無持倉（可能手動平倉），本輪結束")\n                for a in ("pos_open", "pos_px", "pos_tp", "pos_sl", "pos_ee", "pos_pt", "pos_oid"):\n                    S.pop(a, None)\n                save_state(); return\n'
NEWMAN = '            if not p_chk:\n                # 手動平倉也必須入 DB，否則 DB 與 OKX 永遠對不起來\n                log_trade({"date": today8(), "sym": S["sym"], "dir": d, "reason": "Manual_Close",\n                           "ambush_s": round(ee - pt) if pt else 0,\n                           "hold_s": int(time.time() - ee),\n                           "gross": None, "fee": None, "net": None, "nv": None,\n                           "src": "PENDING", "ts": hhmmss(),\n                           "in_ts": datetime.fromtimestamp(ee, TZ8).strftime("%H:%M:%S"),\n                           "tf": S["tf"], "margin": str(S["margin"]),\n                           "in_px": str(fpx), "out_px": None,\n                           "iid": iid, "pos": pos, "t0": int(time.time() * 1000),\n                           "eoid": S.get("pos_oid"), "xoid": None})\n                await notify(app, S["chat"],\n                    f"{E.BOT} {S[\'sym\']} {E.dir_word(d)} OKX 已無持倉（可能手動平倉）\\n"\n                    f"已記入 DB 並標記待補帳，背景任務會向 OKX 取回損益\\n時間：{hhmmss()}")\n                for a in ("pos_open", "pos_px", "pos_tp", "pos_sl", "pos_ee", "pos_pt", "pos_oid"):\n                    S.pop(a, None)\n                save_state(); return\n'
SUMO = '    if pend:\n        L.append("%s 待補帳:%d 筆（未計入損益）" % (E.LOSS, len(pend)))\n    if not m:\n        L.append("尚無已確認損益")\n        return L\n'
SUMN = '    L.append("帳已入DB:%d | 帳未入DB:%d" % (m, len(pend)))\n    if not m:\n        if len(pend):\n            L.append("%s 損益待 OKX 回報後補入" % E.LOSS)\n        else:\n            L.append("本日無進場")\n        return L\n'
AUD = '    L = [f"{E.BOT} OKX原K｜{ACCT}", f"📋 對帳 {t}", "━" * 10,\n         ("%s " % E.LOSS if len(recs) != len(ph) else "") + f"DB筆數：{len(recs)}｜OKX：{len(ph)}",\n         "來源分佈：" + "、".join(f"{k}×{v}" for k, v in srcs.items()),\n         "━" * 10,\n         f"DB 淨損益：{ln:+.6f}",\n         f"OKX 淨損益：{on:+.6f}",\n         f"差異：{ln - on:+.6f}",\n         "━" * 10,\n         f"DB 手續費：{lf:+.6f}",\n         f"OKX 手續費：{of:+.6f}",\n         f"差異：{lf - of:+.6f}",\n         "━" * 10]\n    if len(recs) == len(ph) and abs(ln - on) < Decimal("0.000001") and abs(lf - of) < Decimal("0.000001"):\n        L.append("✅ 完全一致")\n'
AUDO = '    L = [f"{E.BOT} OKX原K｜{ACCT}", f"📋 對帳 {t}", "━" * 10,\n         f"本地筆數：{len(recs)}｜OKX：{len(ph)}",\n         "來源分佈：" + "、".join(f"{k}×{v}" for k, v in srcs.items()),\n         "━" * 10,\n         f"本地淨損益：{ln:+.6f}",\n         f"OKX 淨損益：{on:+.6f}",\n         f"差異：{ln - on:+.6f}",\n         "━" * 10,\n         f"本地手續費：{lf:+.6f}",\n         f"OKX 手續費：{of:+.6f}",\n         f"差異：{lf - of:+.6f}",\n         "━" * 10]\n    if len(recs) != len(ph):\n        L.append(f"{E.LOSS} 筆數不符，OKX 可能尚未完全落帳")\n    elif abs(ln - on) < Decimal("0.000001") and abs(lf - of) < Decimal("0.000001"):\n        L.append("✅ 完全一致")\n    else:\n        L.append(f"{E.LOSS} 有差異，請人工核對")\n'

rep("async def reconcile_pending(app, days=3):", FIND + "async def reconcile_pending(app, days=3):", "1. 插入時間比對函式")
rep(OLDREC, NEWREC, "2. 補帳可處理缺鍵的舊紀錄")
rep(OLDMAN, NEWMAN, "3. 手動平倉也入 DB")
rep(SUMO, SUMN, "4. summary 改帳已入DB/帳未入DB")
rep(AUDO, AUD, "5. audit 改用 DB 用詞與紅燈")

if fails:
    print("\n".join(fails))
    print("=== ABORTED, file NOT modified ===")
    sys.exit(1)

io.open(p, "w", encoding="utf-8").write(s)
print("=== ALL PATCHES APPLIED ===")
